# Generated by Django 6.0.5 on 2026-05-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_type', models.CharField(max_length=100)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_quantity', models.IntegerField()),
            ],
        ),
    ]
